version: '2'
services:
    fullstacktuto-app:
        image: fullstacktuto
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fullstacktuto-postgresql:5432/fullStackTuto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fullstacktuto-postgresql:
        extends:
            file: postgresql.yml
            service: fullstacktuto-postgresql
